# Generated by Django 5.2 on 2025-10-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0025_add_active_session_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='inactive_marked_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
