# Generated by Django 5.2 on 2025-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0026_employeeprofile_inactive_marked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
