# Generated by Django 5.2 on 2025-10-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0027_alter_employeeprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the session is active'),
        ),
    ]
